export const COPY = {
  product: {
    name: '단디 DANDI',
    category: '금융 AI 개인정보 보호 게이트웨이',
    introduction:
      '금융 직원의 AI 요청에서 고객정보를 내부에서 보호하고, AI 응답을 다시 검사해 확인된 업무 결과만 보여주도록 설계한 온프레미스 보호 계층 제안',
    memoryLine: '허용된 업무만, 확인된 결과만',
  },
  scope: {
    badges: ['은행 상담 업무', '개인정보 보호 적용'],
    official: '합성데이터 전용 브라우저 프로토타입 | 로컬 모의 요약 | 서버·외부 AI 없음',
    detail:
      '이 화면은 합성 예시 데이터로 단디의 제품 흐름을 보여줍니다. 실제 고객정보와 금융 시스템에는 연결되지 않습니다.',
    hosting:
      'GitHub Pages 이용 과정에서 GitHub가 접속 정보를 처리할 수 있습니다.',
  },
  workspace: {
    title: '고객 상담 메모를 보호해 요약합니다',
    description: '브라우저 안에서 개인정보 보호, 로컬 모의 요약, 전체 결과 검사를 이어서 실행합니다.',
    start: '개인정보 보호 후 요약 만들기',
    detecting: '합성 개인정보를 찾고 있어요',
    protecting: '정보 유형에 맞게 보호하고 있어요',
    generating: '로컬 모의 요약을 만들고 있어요',
    inspecting: '결과 전체를 확인하고 있어요',
    complete: '전체 검사 완료',
    pass: '확인됨',
    completeDescription: '확인된 결과만 업무 화면에 표시했습니다.',
    reset: '같은 사례 다시 실행',
    another: '다른 합성 사례 실행',
    normal: '정상 합성 사례 보기',
    lockedTitle: '결과를 열기 전이에요',
    lockedDescription: '전체 검사가 끝나면 확인된 결과만 열 수 있어요.',
    recoverableTitle: '실행을 이어가지 못했어요',
    recoverableDescription: '같은 합성 사례를 다시 실행하면 보호 흐름을 처음부터 확인할 수 있어요.',
  },
  functionalPrototype: {
    case: {
      eyebrow: '은행 상담 업무',
      title: '합성 상담 메모',
      selector: '합성 사례 선택',
      sourceDisclosure: '공개 합성 원문',
      syntheticNotice: '실제 고객정보 아님',
      detectedTypesLabel: '찾은 합성 정보 유형',
      typeLabels: {
        name: '이름',
        contact: '연락처',
        account: '계좌정보',
        credential: '인증정보',
      },
      summaryIcon: '요약',
      summaryTitle: '로컬 모의 요약',
      summaryDescription: '보호된 내용만 브라우저 안에서 정리합니다.',
      manualProgress: '단계별 보기',
    },
    gateway: {
      eyebrow: '브라우저 내부 실행',
      title: '개인정보 보호 흐름',
      idleMessage: '요약을 시작하면 다섯 단계를 순서대로 실행합니다.',
      requestBlockedMessage: '지원 범위를 확인해 요약 요청 전에 멈췄습니다.',
      responseWithheldMessage: '검사에서 확인할 항목을 찾아 결과를 잠갔습니다.',
      states: {
        waiting: '대기',
        complete: '완료',
        stopped: '멈춤',
        running: '실행 중',
        skipped: '실행 안 함',
        needsReview: '확인 필요',
        locked: '잠김',
        inProgress: '진행 중',
      },
    },
    protection: {
      title: '보호문 비교',
      requestStopped: '요청 멈춤',
      protected: '보호됨',
      requestBlockedMessage: '지원 범위를 확인해 보호된 요청을 만들지 않았습니다.',
      waitingMessage: '합성 개인정보를 찾은 뒤 보호된 문장을 여기에 표시합니다.',
    },
    inspection: {
      title: '5개 결과 검사',
      confirmed: '확인',
      checkLabels: {
        outputSchema: '결과 형식',
        markerIntegrity: '보호용 표시',
        rawResidue: '원문 흔적',
        sourceGrounding: '입력 근거',
        financialDecision: '금융 판단 제외',
      },
      statuses: {
        waiting: '대기',
        pass: '확인',
        fail: '확인 필요',
      },
    },
    evidence: {
      title: '내용 없는 실행 근거',
      currentSurface: '현재 화면',
    },
    result: {
      eyebrow: '업무 결과',
      title: '상담 요약',
      states: {
        verified: '확인됨',
        requestStopped: '요청 멈춤',
        withheld: '미공개',
        locked: '잠김',
      },
      lockedIcon: '잠금',
      checkingIcon: '확인',
      checkingTitle: '결과를 확인하고 있어요',
      ariaLabel: '확인된 상담 요약 5개 항목',
      needsReviewLabel: '직원이 확인할 항목',
      evidence: {
        syntheticMemo: '합성 상담 메모',
        inputSource: '입력 문장 근거 있음',
        humanReview: '사람이 확인할 항목',
        nextAction: '정해진 다음 행동',
      },
    },
    workspace: {
      eyebrow: '합성 상담 요약',
      profileInitial: '안',
      profile: '브라우저 안에서만 실행',
      actionComplete: '처리 완료',
      actionNext: '다음 단계',
      actionBusy: '브라우저 내부에서 처리 중',
    },
    recoverableEyebrow: '다시 실행할 수 있어요',
  },
  live: {
    started: '단디가 상담 메모의 개인정보 보호 처리를 시작했습니다.',
    verified: '전체 검사가 끝났습니다. 확인된 결과를 표시합니다.',
    withheld: '확인이 필요한 결과는 표시하지 않았습니다.',
    paused: '처리가 일시정지되었습니다. 계속 진행 버튼으로 이어갈 수 있습니다.',
  },
  stageNames: [
    '합성 개인정보 찾기',
    '유형별 보호',
    '로컬 모의 요약',
    '전체 결과 검사',
    '확인된 결과 공개',
  ],
  panels: {
    case: '합성 상담 사례',
    route: '보호 경로',
    result: '업무 결과',
    evidence: '검증 상태',
  },
  controls: {
    play: '재생',
    pause: '일시정지',
    continue: '계속 보기',
    replay: '다시보기',
    previous: '이전',
    next: '다음',
    manual: '단계별 보기',
    blockExample: '확인이 필요한 경우',
    summarize: '개인정보 보호 후 요약 만들기',
  },
  steps: [
    '개요',
    '기존 방식의 빈틈',
    '정보 찾기',
    '유형별 보호',
    '승인 경로',
    '전체 응답 검사',
    '확인된 결과',
    '업무 결과',
    '확인이 필요한 경우',
  ],
  sceneHeadlines: {
    overview: '상담 직원의 AI 요약, 고객정보는 내부에 남겨야 합니다',
    gap: '직접 삭제는 확인 작업이 생기고, 모두 차단하면 상담요약도 멈춥니다',
    detect: '이름·연락처·계좌가 한 문장에 섞여 있습니다',
    protect: '정보 유형에 맞게 보호합니다',
    route: '이 정적 시연에서는 외부 AI·API 경로를 사용하지 않습니다',
    inspect: '응답 전체를 확인하는 동안 결과는 열지 않습니다',
    result: '확인된 요약과 직원 확인 항목을 함께 보여줍니다',
    finish: '입력 보호에서 끝나지 않고, 결과 공개 전까지 왕복 전체를 확인합니다',
    withheld: '확인이 필요한 결과는 표시하지 않았어요',
  },
  case: {
    caseIdLabel: '사례 ID',
    classification: '처음부터 만든 가상 합성 사례',
    sourceLabel: '합성 상담 메모',
    protectedLabel: '보호된 요청',
  },
  problem: {
    manual: '직접 삭제: 확인 작업과 누락 가능성',
    blockAll: '요청 전체 차단: 상담요약 업무도 중단',
    core: '보호한 요청이 확인된 업무 결과로 끝났는지 함께 확인해야 합니다',
  },
  protection: {
    detect: '찾기',
    protectByType: '정보 유형별 보호',
    entities: [
      {type: '이름', action: '요청별 가상값으로 바꿈'},
      {type: '연락처', action: '연락처 유형 표식으로 바꿈'},
      {type: '계좌', action: '계좌 유형 표식으로 바꿈'},
    ],
    matrix: {
      eyebrow: '유형별 보호',
      title: '정보 유형별 정책 예시',
      description:
        '직접 식별자, 준식별자, 민감 정보, 비개인정보의 고위험, 중위험, 저위험 수준을 구분하고 연결 보호, 선택적 보호, 강화 보호, 일반 제공을 검토합니다.',
      methods: ['마스킹', '가명처리', '비식별화', '토큰화', '원문 제공'],
      disclaimer: '정책 시뮬레이션이며 실제 처리 성능을 뜻하지 않습니다',
    },
  },
  route: {
    external: '외부 AI·API 경로',
    externalState: '사용하지 않음',
    internal: '내부·모의 처리 경로',
    internalState: '승인된 시연 경로',
    payloadState: '외부로 이동한 요청 없음',
  },
  inspection: {
    title: '전체 응답 검사',
    waiting: '검사가 끝날 때까지 업무 결과를 열지 않습니다',
    exact: '정확히 연결됨 → 결과 공개',
    changed: '형태가 달라짐 → 결과 미공개',
    complete: '전체 응답을 확인했어요',
    checks: [
      ['정책 준수 검사', '허용된 업무 범위 내 처리 확인'],
      ['개인정보 표식 검사', '이름·연락처·계좌 표식 확인'],
      ['민감정보 패턴 검사', '거래내역·신용정보 패턴 확인'],
      ['외부 경로 검사', '외부 이동 0 확인'],
      ['응답 무결성 검사', '응답 구조와 위변조 확인'],
      ['최종 안전성 판단', '공개 또는 결과 미공개 결정'],
    ],
    fixedDemoNotice:
      '표시된 진행률과 상태 수치는 가상 시연을 위한 고정값이며 제품 성능이나 운영 검증 결과가 아닙니다.',
  },
  verifiedResult: [
    {
      label: '상담 목적',
      value: '자동이체 오류 상담',
      evidence: '합성 상담 메모',
    },
    {
      label: '고객 요청',
      value: '오류 확인과 처리 결과 안내',
      evidence: '합성 상담 메모',
    },
    {
      label: '직원이 안내한 내용',
      value: '내부 조회 후 처리 결과를 안내하기로 함',
      evidence: '입력 문장 근거 있음',
    },
    {
      label: '직원이 확인할 항목',
      value: '정확한 오류 원인과 처리 완료 여부',
      evidence: '사람이 확인할 항목',
    },
    {
      label: '다음 조치',
      value: '내부 조회 후 합성연락처-001로 안내',
      evidence: '합성 상담 메모',
    },
  ],
  resultEffect: '직원이 확인할 항목은 구분해서 함께 보여줍니다',
  blocked: {
    requestEyebrow: '요약 요청 전 확인',
    requestTitle: '이 합성 사례는 요약 요청 전에 멈췄어요',
    requestDescription: '지원하지 않는 고위험 정보 유형을 확인해 모의 요약 단계로 보내지 않았습니다.',
    responseEyebrow: '결과 미공개',
    responseTitle: '보호용 표시를 확인하기 어려워 결과를 열지 않았어요',
    responseDescription: '확인이 필요한 결과는 업무 화면에 표시하지 않았습니다. 다른 합성 사례를 확인할 수 있어요.',
  },
  finalFlow: ['요청 정보 보호', '승인 경로', '전체 응답 검사', '확인된 결과 공개'],
  evidence: {
    storageLabel: '저장 상태',
    storageValue: '브라우저 저장소 쓰기 없음',
    serverLabel: '서버 연결',
    serverValue: '연결 없음',
    externalLabel: '외부 AI 연결',
    externalValue: '연결 없음',
    executionLabel: '실행 위치',
    executionValue: '브라우저 내부 실행',
  },
  validation: {
    title: '은행 상담 업무',
    people: '상담 메모',
    tasks: 'AI 상담 요약',
    comparison: '개인정보 보호부터 결과 확인까지 한 화면에서 이어집니다',
    measures: ['정보 찾기', '유형별 보호', 'AI 작성', '응답 검사', '결과 공개'],
  },
  bootstrap: {
    loading: '합성 사례를 확인하고 있어요',
    emptyTitle: '표시할 합성 사례가 없어요',
    emptyDescription: '승인된 시연 데이터가 준비되면 같은 보호 흐름을 바로 확인할 수 있어요.',
    emptyAction: '데모 다시 확인',
    invalidTitle: '검수된 시연 데이터를 확인하지 못했어요',
    invalidDescription: '데모를 다시 시작해 주세요. 일부 데이터만 표시하지는 않아요.',
    invalidAction: '처음부터 다시 시작',
    paused: '데모가 멈춰 있어요',
    reducedMotion: '단계별로 편하게 확인할 수 있어요',
  },
} as const;

export const FORBIDDEN_RENDERED_COPY = [
  '—',
  '100% 안전',
  '완전 차단',
  '유출 0',
  '운영 완료',
  '검증 완료',
  'Zero-Knowledge',
  'Aegis AI',
  'ChatGPT',
  'OpenAI',
  'iM금융',
  'iM뱅크',
] as const;

export type VerifiedResultField = (typeof COPY.verifiedResult)[number];
